const IMAGE_SERVER = "https://api.nomoreparties.co";

// ЛЕЙАУТ ДЛЯ ДЕСКТОПА
const DESKTOP_RESOLUTION = 1280;
const DESKTOP_CARDS_CNT = 4;
const DESKTOP_LOAD_MORE_CARDS_CNT = 3;

// ЛЕЙАУТ ДЛЯ ПЛАНШЕТА
const TAB_RESOLUTION = 768;
const TAB_CARDS_CNT = 4;
const TAB_LOAD_MORE_CARDS_CNT = 2;

// ЛЕЙАУТ ДЛЯ МОБИЛЬНОГО
const MOBILE_RESOLUTION = 480;
const MOBILE_CARDS_CNT = 5;
const MOBILE_LOAD_MORE_CARDS_CNT = 2;

module.exports = {

  IMAGE_SERVER,

  DESKTOP_RESOLUTION,
  DESKTOP_CARDS_CNT,
  DESKTOP_LOAD_MORE_CARDS_CNT,
  TAB_RESOLUTION,
  TAB_CARDS_CNT,
  TAB_LOAD_MORE_CARDS_CNT,
  MOBILE_RESOLUTION,
  MOBILE_CARDS_CNT,
  MOBILE_LOAD_MORE_CARDS_CNT,
};
